language: R
sudo: false
cache: packages
r_github_packages:
- hadley/pkgdown
r_packages:
- packagedocs
env:
  global:
    secure: mvPW0K9aR+S0HIhRd7x8ylF/Eu3u/hiks5xc8Xxz/rF/UWuGihDk0v0qpsdfAbgPW8CsAimXL9dFL6EwB23g226VXTixHdPgtKULYxLd074FWT7saaz9Hntt3Bsru+iumVU77OEjnPePKtYO7kNj1Vu3DW9SDYxxJXhM/NU9FtBp0ovffdt9f3gcOHRxDIks0/B/OtF4UvyEZMNn/U0qx4Ro0iJWu5nV0KKvQ/LALreaApZhP65ibkDAF/xNa7Rlvo5HPgn/g2efsKTl829mpPTCAzM7w6ybeQjQw+D/NyUr3ZvLo8QdSdIhWlopbstQkhktVQwxhzk2krpipThxnVKv4JB8tFhktNlHR0RGT0tTRj8425wQra8xjT394wSbAfFMbZDfkvXarozVuoxEFhBrgIiGldNkWl+ubfAiIxL0XnPu0UbZkv4lb/B+MVihOtmVik2bhQvURJ0RUIx1yaADr5tkZaXtfJJVAKTMsGPjXqvtU7p98QEEevu5XXZDuQaiTZyWkF7+4JNgYQt/nZPt0w6YXCBx1T71H4aZjWxVK/2VNR3HCZzHSg+a820THJ53hq9rqZZ3VD/vX7ZNMjXYZcb0lquh0CpqnhD5Hs11MQYuOpxrwR432gqOZgpT9OotW402aIVMKPrPFqfpdwijld9xYJD9ODw+N+PEVQc=
after_success:
- Rscript -e "packagedocs::deploy_travis(repo = 'AliciaSchep/rdummypkg', build_fn = function(output_dir, ...){devtools::install('.'); pkgdown::build_site(path = output_dir)})"
